### ISSUE TITLE
Support for Emacs

### ISSUE THREAD

**Issue by arybczak** [coot/ghc-tags-plugin#16]
It would be great to have a configuration toggle for generation of Emacs compatible tags :pray:

**Comment by coot** [comment]
Yes, that's planned.  There's place for that, `vim` stuff is encapsulated in `GhcTags.Plugin.Vim` (parser + formatter), and we need to the same for emacs, plugged it in (and add a command line parser).

**Comment by coot** [comment]
Done in #22.
