### ISSUE TITLE
Tags are not compatible with the output of universal-ctags

### ISSUE THREAD

**Issue by arybczak** [coot/ghc-tags-plugin#23]
In both ways, i.e. `ctags -a` doesn't work on `tags` generated by the plugin and the plugin can't parse `tags` file generated by `ctags`.

The former is easily solvable by adding `//` to header lines:
```diff
diff --git a/lib/Plugin/GhcTags/CTags/Formatter.hs b/lib/Plugin/GhcTags/CTags/Formatter.hs
index 5f126e8..dbd7e67 100644
--- a/lib/Plugin/GhcTags/CTags/Formatter.hs
+++ b/lib/Plugin/GhcTags/CTags/Formatter.hs
@@ -79,7 +79,7 @@ formatField TagField { fieldName, fieldValue } =
 
 
 formatHeader :: String -> String -> String
-formatHeader header arg = printf ("!_" ++ header ++ "\t%s\t" ++ endOfLine) arg
+formatHeader header arg = printf ("!_" ++ header ++ "\t%s\t//" ++ endOfLine) arg
 
 formatHeaders :: Builder
 formatHeaders =
```

I'm not sure what about the latter.

**Comment by coot** [comment]
Can you share the `ctag` file that cannot be parsed? I tested it with `tags` generated from `vim` project.

**Comment by arybczak** [comment]
Sure, here it is: https://pastebin.com/RrCPXMfP

**Comment by coot** [comment]
That's because the header parser tripped over '!_TAG_OUTPUT_` header.  I need to add a proper header parser (#30).
