### ISSUE TITLE
Make ghc-tags-core thinner

### ISSUE THREAD

**Issue by arybczak** [coot/ghc-tags-plugin#35]
Thanks for splitting it, though I find that some of things there are still tied to ghc-tags-plugin.
- `pipes` dependency is redundant really since you can read a file, call `parseTagsFile` and you're done.
- I'd like a parser ideally to give me `Map FilePath Tag` (maybe even `Map Text Tag` since StringS suck) and Tag not having file path inside. This needs less memory for storage and replacing tags from specific file is much faster than using `combineTags` (might not be a big deal for a plugin that deals with one file, but I'm processing multiple files).

Since there might be some more incompatibilities and I don't want to impose any changes on you, perhaps it'd be best to make `ghc-tags-core` have only `GhcTags.Ghc` module?

**Comment by arybczak** [comment]
Though I'd say that `plugin` would benefit from both of these. Especially not storing file names as `String`, I had them stored as `Text` locally and when I adjusted to `ghc-core-plugin` I saw that things got slower and ate more memory.

**Comment by arybczak** [comment]
Actually nevermind, I think the correct way forward is for me to work with a local copy of ghc-tags-core for now, make changes I want for ghc-tags to be efficient and then we can integrate them into ghc-tags-core proper.

**Comment by coot** [comment]
Both points are valid, so I'd be happy to accept a patch (or I'll do that myself at some point).
