### ISSUE TITLE
Explicitly passing ghc-options -j breaks multithread synchronisation

### ISSUE THREAD

**Issue by hseg** [coot/ghc-tags-plugin#43]
With `ghc-options: -j` in my `.cabal` file, `ghc-tags-plugin` complains
```./.tags.lock: openFile: resource busy (file is locked)```
However, this can be worked around by doing the right thing and setting `jobs: $ncpus` in `cabal.project.local`.
Despite this, might want to look into the synchronization logic.
In any case, leaving this here in case someone else bumps into this problem.

**Comment by coot** [comment]
Which version of `ghc-tags-plugin` didn't work fork you? Have you tried `v0.2.2`?

**Comment by hseg** [comment]
Failed on 0.2.0, couldn't reproduce on 0.2.2
Sorry for the noise 

On July 21, 2020 5:30:48 PM GMT+03:00, Marcin Szamotulski <notifications@github.com> wrote:
>Which version of `ghc-tags-plugin` didn't work fork you? Have you tried
>`v0.2.2`?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/coot/ghc-tags-plugin/issues/43#issuecomment-661896650

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by coot** [comment]
Good to know, cheers.
